# Export POC-ABS dari apex event clips ke satu XLSX

Pipeline:
1. Baca `output/apex/metadata.xlsx`
2. Ambil semua clip event dari `output/apex/dataset/.../event_*`
3. Per event clip: frame pertama = baseline, frame berikutnya = POC-ABS flatten
4. Gabung semua row jadi **satu XLSX**
5. Urutkan per partisipan / label / pertanyaan dari **before → after**

In [1]:
import os
import re
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
import pandas as pd

ROOT = Path.cwd().resolve()
if ROOT.name == 'preprocess-anxiety':
    ROOT = ROOT.parent.resolve()

os.chdir(ROOT)
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

print(f'Project root: {ROOT}')

Project root: /home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st

In [2]:
from comparasion.core.config import ComparisonConfig
from comparasion.core.roi import ROIExtractor
from features_extraction.poc import POC
from features_extraction.quadran import Quadran
from features_extraction.vektor import Vektor

In [3]:
DATASET_ROOT = (ROOT / 'output/apex/dataset').resolve()
METADATA_PATH = (ROOT / 'output/apex/metadata.xlsx').resolve()
OUTPUT_DIR = (ROOT / 'output/apex/features').resolve()
OUTPUT_PATH = OUTPUT_DIR / 'poc_abs_flatten_ordered.xlsx'
MAX_WORKERS = min(8, os.cpu_count() or 1)

REGIONS = {
    'mulut': list(range(48, 68)),
    'mata_kiri': list(range(17, 22)) + list(range(36, 42)),
    'mata_kanan': list(range(22, 27)) + list(range(42, 48)),
}

TARGET_SIZE = {
    'mulut': (70, 35),
    'mata_kiri': (48, 32),
    'mata_kanan': (48, 32),
}

config = ComparisonConfig(
    output_root=Path('output/apex/tmp_compare'),
    regions=REGIONS,
    target_size=TARGET_SIZE,
)

print(f'Dataset root: {DATASET_ROOT}')
print(f'Metadata:     {METADATA_PATH}')
print(f'Output xlsx:  {OUTPUT_PATH}')
print(f'Max workers:  {MAX_WORKERS}')
print(f'Regions:      {list(config.regions.keys())}')
print(f'Target size:  {config.target_size}')
print(f'Block size:   {config.block_size}')

Dataset root: /home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st/output/apex/dataset
Metadata:     /home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st/output/apex/metadata.xlsx
Output xlsx:  /home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st/output/apex/features/poc_abs_flatten_ordered.xlsx
Max workers:  8
Regions:      ['mulut', 'mata_kiri', 'mata_kanan']
Target size:  {'mulut': (70, 35), 'mata_kiri': (48, 32), 'mata_kanan': (48, 32)}
Block size:   7

In [4]:
if not DATASET_ROOT.exists():
    raise FileNotFoundError(f'Dataset root not found: {DATASET_ROOT}')
if not METADATA_PATH.exists():
    raise FileNotFoundError(f'Metadata not found: {METADATA_PATH}')
if not config.predictor_path.exists():
    raise FileNotFoundError(f'Predictor not found: {config.predictor_path}')

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
metadata = pd.read_excel(METADATA_PATH)
print(f'Metadata rows: {len(metadata)}')
metadata.head(2)

Metadata rows: 2764

,relative_sample,source_video,event_no,onset_signal,apex_signal,offset_signal,onset_frame,apex_frame,offset_frame,duration,saved_frames,window_length,polyorder,height_threshold,clip_dir
0,after/anxiety/aaisyah_nursalsabiil_ni_patriart...,/home/ryuko/Documents/Codes/Python/Skripsi/Con...,1,93,98,103,94,99,104,10,11,17,4,0.171891,dataset/after/anxiety/aaisyah_nursalsabiil_ni_...
1,after/anxiety/aaisyah_nursalsabiil_ni_patriart...,/home/ryuko/Documents/Codes/Python/Skripsi/Con...,2,175,205,212,176,206,213,37,38,17,4,0.171891,dataset/after/anxiety/aaisyah_nursalsabiil_ni_...

In [5]:
@dataclass(slots=True)
class EventClip:
    phase: str
    condition: str
    label: str
    participant_raw: str
    participant_key: str
    question: str
    question_no: int
    sample_name: str
    clip_name: str
    event_clip: str
    event_no: int
    event_dir: Path
    onset_frame: int
    apex_frame: int
    offset_frame: int

    @property
    def sample_id(self) -> str:
        return f'{self.phase}__{self.condition}__{self.participant_raw}__{self.question}__{self.sample_name}__event_{self.event_no:03d}'


def natural_sort_key(value: str):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', value)]


def parse_question_no(question: str) -> int:
    match = re.search(r'(\d+)', question)
    return int(match.group(1)) if match else 0


def normalize_participant_key(name: str) -> str:
    return re.sub(r'_[0-9]+$', '', name)


def map_label(condition: str) -> str:
    mapping = {
        'anxiety': 'anxiety_tinggi',
        'tidak': 'anxiety_rendah',
    }
    return mapping.get(condition, condition)


def parse_event_dir(clip_dir_value: str) -> Path:
    raw = Path(str(clip_dir_value).replace('\\', '/'))
    parts = raw.parts

    if raw.is_absolute():
        return raw.resolve()

    if parts[:3] == ('output', 'apex', 'dataset'):
        raw = Path(*parts[3:])
    elif parts and parts[0] == 'dataset':
        raw = Path(*parts[1:])

    return (DATASET_ROOT / raw).resolve()


def build_event_clips(df: pd.DataFrame) -> list[EventClip]:
    clips: list[EventClip] = []
    valid = df[df['clip_dir'].notna()].copy()

    for row in valid.itertuples(index=False):
        parts = Path(row.relative_sample).parts
        if len(parts) < 5:
            continue

        phase, condition, participant_raw, question, sample_name = parts[:5]
        event_dir = parse_event_dir(row.clip_dir)
        clips.append(EventClip(
            phase=phase,
            condition=condition,
            label=map_label(condition),
            participant_raw=participant_raw,
            participant_key=normalize_participant_key(participant_raw),
            question=question,
            question_no=parse_question_no(question),
            sample_name=sample_name,
            clip_name=sample_name,
            event_clip=event_dir.name,
            event_no=int(row.event_no),
            event_dir=event_dir,
            onset_frame=int(row.onset_frame),
            apex_frame=int(row.apex_frame),
            offset_frame=int(row.offset_frame),
        ))

    return sorted(
        clips,
        key=lambda c: (
            c.participant_key,
            c.label,
            c.question_no,
            0 if c.phase == 'before' else 1,
            natural_sort_key(c.clip_name),
            c.event_no,
            natural_sort_key(c.event_clip),
        ),
    )


event_clips = build_event_clips(metadata)
print(f'Event clips: {len(event_clips)}')
event_clips[:3]

Event clips: 2764

[EventClip(phase='before', condition='anxiety', label='anxiety_tinggi', participant_raw='aaisyah_nursalsabiil_ni_patriarti_1765168488512', participant_key='aaisyah_nursalsabiil_ni_patriarti', question='q1', question_no=1, sample_name='answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec', clip_name='answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec', event_clip='event_00054-00095', event_no=1, event_dir=PosixPath('/home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st/output/apex/dataset/before/anxiety/aaisyah_nursalsabiil_ni_patriarti_1765168488512/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00054-00095'), onset_frame=54, apex_frame=65, offset_frame=95),
 EventClip(phase='before', condition='anxiety', label='anxiety_tinggi', participant_raw='aaisyah_nursalsabiil_ni_patriarti_1765168488512', participant_key='aaisyah_nursalsabiil_ni_patriarti', question='q1', question_no=1, sample_name='answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec', clip_name='answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec', event_clip='event_00153-00166', event_no=2, event_dir=PosixPath('/home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st/output/apex/dataset/before/anxiety/aaisyah_nursalsabiil_ni_patriarti_1765168488512/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00153-00166'), onset_frame=153, apex_frame=160, offset_frame=166),
 EventClip(phase='before', condition='anxiety', label='anxiety_tinggi', participant_raw='aaisyah_nursalsabiil_ni_patriarti_1765168488512', participant_key='aaisyah_nursalsabiil_ni_patriarti', question='q1', question_no=1, sample_name='answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec', clip_name='answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec', event_clip='event_00173-00187', event_no=3, event_dir=PosixPath('/home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st/output/apex/dataset/before/anxiety/aaisyah_nursalsabiil_ni_patriarti_1765168488512/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00173-00187'), onset_frame=173, apex_frame=182, offset_frame=187)]

In [6]:
WORKER_EXTRACTOR = None
WORKER_CONFIG = None


def init_worker() -> None:
    global WORKER_EXTRACTOR, WORKER_CONFIG
    WORKER_CONFIG = ComparisonConfig(
        output_root=Path('output/apex/tmp_compare'),
        regions=REGIONS,
        target_size=TARGET_SIZE,
        padding_x=config.padding_x,
        padding_y=config.padding_y,
        block_size=config.block_size,
        predictor_path=config.predictor_path,
        feature_method=config.feature_method,
        include_quadrant_counts=config.include_quadrant_counts,
    )
    WORKER_EXTRACTOR = ROIExtractor(WORKER_CONFIG)


def load_event_frames(event_dir: Path) -> tuple[list[np.ndarray], list[Path]]:
    frame_paths = sorted(
        [p for p in event_dir.iterdir() if p.is_file() and p.suffix.lower() in {'.jpg', '.jpeg', '.png'}],
        key=lambda p: natural_sort_key(p.name),
    )
    if len(frame_paths) < 2:
        raise ValueError(f'Need >= 2 frames: {event_dir}')

    frames = []
    for path in frame_paths:
        image = cv2.imread(str(path))
        if image is None:
            raise FileNotFoundError(f'Failed to read image: {path}')
        frames.append(image)
    return frames, frame_paths


def to_gray(image: np.ndarray) -> np.ndarray:
    if image.ndim == 2:
        return image
    return cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)


def extract_flatten_row(clip: EventClip, frame_no: int, rois: dict[str, np.ndarray], baseline_gray: dict[str, np.ndarray], block_size: int) -> dict:
    row = {
        'phase': clip.phase,
        'condition': clip.condition,
        'label': clip.label,
        'participant': clip.participant_key,
        'participant_raw': clip.participant_raw,
        'question': clip.question,
        'question_no': clip.question_no,
        'sample': clip.sample_name,
        'clip': clip.clip_name,
        'event_clip': clip.event_clip,
        'event_no': clip.event_no,
        'clip_path': str(clip.event_dir.resolve().relative_to(ROOT.resolve())),
        'frame': frame_no,
    }

    for comp in WORKER_CONFIG.regions:
        gray = to_gray(rois[comp])
        poc = POC(baseline_gray[comp], gray, block_size)
        vec = Vektor(poc.getPOC(), block_size)
        quad = Quadran(vec.getVektor()).getQuadran()

        for block_id, block in enumerate(quad, start=1):
            row[f'{comp}_x{block_id}'] = block[1]
            row[f'{comp}_y{block_id}'] = block[2]
            row[f'{comp}_t{block_id}'] = block[3]
            row[f'{comp}_m{block_id}'] = block[4]

    return row


def process_event_clip(clip: EventClip) -> list[dict]:
    frames, _frame_paths = load_event_frames(clip.event_dir)

    rois_per_frame: list[dict[str, np.ndarray] | None] = []
    for frame in frames:
        try:
            rois_per_frame.append(WORKER_EXTRACTOR.extract_rois(frame))
        except ValueError:
            rois_per_frame.append(None)

    baseline_rois = rois_per_frame[0]
    if baseline_rois is None:
        raise ValueError(f'No face detected in baseline frame: {clip.event_dir}')

    baseline_gray = {name: to_gray(img) for name, img in baseline_rois.items()}
    rows: list[dict] = []

    for idx in range(1, len(frames)):
        rois = rois_per_frame[idx]
        if rois is None:
            continue

        frame_no = idx + 1
        rows.append(extract_flatten_row(clip, frame_no, rois, baseline_gray, WORKER_CONFIG.block_size))

    return rows


def worker_task(clip: EventClip) -> tuple[EventClip, list[dict] | None, str | None]:
    try:
        return clip, process_event_clip(clip), None
    except Exception as exc:
        return clip, None, str(exc)

In [7]:
all_rows = []
errors = []

with ProcessPoolExecutor(max_workers=MAX_WORKERS, initializer=init_worker) as executor:
    futures = [executor.submit(worker_task, clip) for clip in event_clips]

    for idx, future in enumerate(futures, start=1):
        clip, rows, error = future.result()
        print(f'[{idx}/{len(event_clips)}] {clip.phase}/{clip.label}/{clip.participant_key}/{clip.question}/{clip.clip_name}/{clip.event_clip}/event_{clip.event_no:03d}')
        if error is not None:
            errors.append((clip.sample_id, error))
            continue
        all_rows.extend(rows)

print(f'Rows collected: {len(all_rows)}')
print(f'Errors: {len(errors)}')

[1/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00054-00095/event_001
[2/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00153-00166/event_002
[3/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00173-00187/event_003
[4/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00253-00272/event_004
[5/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00284-00313/event_005
[6/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00160-00186/event_001
[7/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00610-00628/event_002
[8/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00698-00716/event_003
[9/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00823-00849/event_004
[10/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00890-00933/event_005
[11/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00335-00352/event_001
[12/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00371-00390/event_002
[13/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00418-00440/event_003
[14/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00535-00574/event_004
[15/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00587-00597/event_005
[16/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00056-00073/event_001
[17/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00092-00113/event_002
[18/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00213-00221/event_003
[19/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00347-00365/event_004
[20/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00496-00513/event_005
[21/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00070-00112/event_001
[22/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00166-00199/event_002
[23/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00209-00243/event_003
[24/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00357-00368/event_004
[25/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00421-00440/event_005
[26/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00094-00104/event_001
[27/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00176-00213/event_002
[28/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00224-00239/event_003
[29/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00256-00267/event_004
[30/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00274-00293/event_005
[31/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00110-00148/event_001
[32/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00173-00191/event_002
[33/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00382-00409/event_003
[34/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00600-00621/event_004
[35/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00635-00666/event_005
[36/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00047-00080/event_001
[37/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00086-00102/event_002
[38/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00217-00251/event_003
[39/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00325-00345/event_004
[40/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00466-00493/event_005
[41/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00026-00042/event_001
[42/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00094-00128/event_002
[43/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00263-00282/event_003
[44/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00299-00313/event_004
[45/2764] before/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00333-00405/event_005
[46/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00007-00049/event_001
[47/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00050-00068/event_002
[48/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00125-00143/event_003
[49/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00185-00208/event_004
[50/2764] after/anxiety_tinggi/aaisyah_nursalsabiil_ni_patriarti/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00267-00273/event_005
[51/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00227-00267/event_001
[52/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00293-00316/event_002
[53/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00330-00350/event_003
[54/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00398-00429/event_004
[55/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00493-00507/event_005
[56/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00019-00039/event_001
[57/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00050-00063/event_002
[58/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00170-00191/event_003
[59/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00260-00282/event_004
[60/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00292-00310/event_005
[61/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00001-00019/event_001
[62/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00019-00031/event_002
[63/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00036-00056/event_003
[64/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00066-00127/event_004
[65/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00336-00390/event_005
[66/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00024-00062/event_001
[67/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00089-00116/event_002
[68/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00171-00190/event_003
[69/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00224-00239/event_004
[70/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00254-00309/event_005
[71/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00165-00187/event_001
[72/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00195-00204/event_002
[73/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00214-00224/event_003
[74/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00244-00260/event_004
[75/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00260-00319/event_005
[76/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00148-00174/event_001
[77/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00176-00193/event_002
[78/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00199-00236/event_003
[79/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00273-00306/event_004
[80/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00113-00129/event_001
[81/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00147-00174/event_002
[82/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00288-00353/event_003
[83/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00456-00472/event_004
[84/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00473-00501/event_005
[85/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00048-00071/event_001
[86/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00087-00096/event_002
[87/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00098-00134/event_003
[88/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00168-00177/event_004
[89/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00180-00194/event_005
[90/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00129-00144/event_001
[91/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00169-00188/event_002
[92/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00189-00205/event_003
[93/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00245-00258/event_004
[94/2764] before/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00362-00381/event_005
[95/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00001-00032/event_001
[96/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00208-00219/event_002
[97/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00220-00230/event_003
[98/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00234-00246/event_004
[99/2764] after/anxiety_tinggi/abdillah_agil_arbiansyah/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00253-00264/event_005
[100/2764] after/anxiety_rendah/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00006-00024/event_001
[101/2764] after/anxiety_rendah/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00201-00227/event_002
[102/2764] after/anxiety_rendah/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00237-00259/event_003
[103/2764] after/anxiety_rendah/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00259-00269/event_004
[104/2764] after/anxiety_rendah/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00299-00310/event_005
[105/2764] after/anxiety_rendah/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00005-00025/event_001
[106/2764] after/anxiety_rendah/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00107-00114/event_002
[107/2764] after/anxiety_rendah/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00144-00152/event_003
[108/2764] after/anxiety_rendah/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00175-00188/event_004
[109/2764] after/anxiety_rendah/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00193-00210/event_005
[110/2764] after/anxiety_rendah/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00131-00143/event_001
[111/2764] after/anxiety_rendah/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00154-00169/event_002
[112/2764] after/anxiety_rendah/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00178-00191/event_003
[113/2764] after/anxiety_rendah/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00208-00219/event_004
[114/2764] after/anxiety_rendah/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00220-00238/event_005
[115/2764] after/anxiety_rendah/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00027-00040/event_001
[116/2764] after/anxiety_rendah/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00052-00059/event_002
[117/2764] after/anxiety_rendah/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00066-00078/event_003
[118/2764] after/anxiety_rendah/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00089-00100/event_004
[119/2764] after/anxiety_rendah/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00104-00111/event_005
[120/2764] after/anxiety_rendah/abdul_aziz/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00027-00047/event_001
[121/2764] after/anxiety_rendah/abdul_aziz/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00072-00096/event_002
[122/2764] after/anxiety_rendah/abdul_aziz/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00124-00133/event_003
[123/2764] after/anxiety_rendah/abdul_aziz/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00138-00153/event_004
[124/2764] after/anxiety_rendah/abdul_aziz/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00288-00299/event_005
[125/2764] before/anxiety_tinggi/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00021-00036/event_001
[126/2764] before/anxiety_tinggi/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00040-00058/event_002
[127/2764] before/anxiety_tinggi/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00086-00109/event_003
[128/2764] before/anxiety_tinggi/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00201-00228/event_004
[129/2764] before/anxiety_tinggi/abdul_aziz/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00333-00354/event_005
[130/2764] before/anxiety_tinggi/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00090-00133/event_001
[131/2764] before/anxiety_tinggi/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00203-00225/event_002
[132/2764] before/anxiety_tinggi/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00243-00268/event_003
[133/2764] before/anxiety_tinggi/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00274-00288/event_004
[134/2764] before/anxiety_tinggi/abdul_aziz/q2/answer_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_sec/event_00298-00311/event_005
[135/2764] before/anxiety_tinggi/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00078-00104/event_001
[136/2764] before/anxiety_tinggi/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00121-00129/event_002
[137/2764] before/anxiety_tinggi/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00173-00203/event_003
[138/2764] before/anxiety_tinggi/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00259-00307/event_004
[139/2764] before/anxiety_tinggi/abdul_aziz/q3/answer_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_sec/event_00396-00437/event_005
[140/2764] before/anxiety_tinggi/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00008-00018/event_001
[141/2764] before/anxiety_tinggi/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00033-00043/event_002
[142/2764] before/anxiety_tinggi/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00130-00141/event_003
[143/2764] before/anxiety_tinggi/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00142-00152/event_004
[144/2764] before/anxiety_tinggi/abdul_aziz/q4/answer_4_497eb431-dd00-4530-858f-e8ec710014e7_sec/event_00160-00163/event_005
[145/2764] before/anxiety_tinggi/abdul_aziz/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00041-00108/event_001
[146/2764] before/anxiety_tinggi/abdul_aziz/q5/answer_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_sec/event_00160-00189/event_002

In [8]:
if errors:
    error_df = pd.DataFrame(errors, columns=['sample_id', 'error'])
    print(error_df.head(20).to_string(index=False))
    error_df.head(20)

                                                                                                            sample_id                                                                                                                                                                                                                                  error
before__tidak__ashrul_rifki_ardiyhasa_1765264624251__q1__answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec__event_002 No face detected in baseline frame: /home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st/output/apex/dataset/before/tidak/ashrul_rifki_ardiyhasa_1765264624251/q1/answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec/event_00102-00124

In [9]:
df = pd.DataFrame(all_rows)
if df.empty:
    raise ValueError('No rows produced.')

df = df.sort_values(
    by=['participant', 'label', 'question_no', 'phase', 'clip', 'event_clip', 'event_no', 'frame'],
    key=lambda s: s.map({'before': 0, 'after': 1}) if s.name == 'phase' else s,
    kind='stable',
).reset_index(drop=True)

df.to_excel(OUTPUT_PATH, index=False)
print(f'Saved: {OUTPUT_PATH}')
print(f'Shape: {df.shape}')
df.head()

Saved: /home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st/output/apex/features/poc_abs_flatten_ordered.xlsx
Shape: (57656, 405)

,phase,condition,label,participant,participant_raw,question,question_no,sample,clip,event_clip,...,mata_kanan_t22,mata_kanan_m22,mata_kanan_x23,mata_kanan_y23,mata_kanan_t23,mata_kanan_m23,mata_kanan_x24,mata_kanan_y24,mata_kanan_t24,mata_kanan_m24
0,before,anxiety,anxiety_tinggi,aaisyah_nursalsabiil_ni_patriarti,aaisyah_nursalsabiil_ni_patriarti_1765168488512,q1,1,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,event_00054-00095,...,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0
1,before,anxiety,anxiety_tinggi,aaisyah_nursalsabiil_ni_patriarti,aaisyah_nursalsabiil_ni_patriarti_1765168488512,q1,1,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,event_00054-00095,...,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0
2,before,anxiety,anxiety_tinggi,aaisyah_nursalsabiil_ni_patriarti,aaisyah_nursalsabiil_ni_patriarti_1765168488512,q1,1,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,event_00054-00095,...,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0
3,before,anxiety,anxiety_tinggi,aaisyah_nursalsabiil_ni_patriarti,aaisyah_nursalsabiil_ni_patriarti_1765168488512,q1,1,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,event_00054-00095,...,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0
4,before,anxiety,anxiety_tinggi,aaisyah_nursalsabiil_ni_patriarti,aaisyah_nursalsabiil_ni_patriarti_1765168488512,q1,1,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec,event_00054-00095,...,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0

In [11]:
PHASE_SORT = {'before': 0, 'after': 1}

df_phase_first = df.assign(
    _phase_order=df['phase'].map(PHASE_SORT).fillna(99),
).sort_values(
    by=['_phase_order', 'participant', 'label', 'question_no', 'clip', 'event_clip', 'event_no', 'frame'],
    kind='stable',
).drop(columns=['_phase_order']).reset_index(drop=True)

df_phase_first.to_excel(OUTPUT_PATH, index=False)
df = df_phase_first

print(f'Re-saved with phase-first ordering: {OUTPUT_PATH}')
print(df[['phase', 'participant', 'label', 'question', 'clip', 'event_clip', 'event_no', 'frame']].head(20).to_string(index=False))

Re-saved with phase-first ordering: /home/ryuko/Documents/Codes/Python/Skripsi/Convat-1st/output/apex/features/poc_abs_flatten_ordered.xlsx
 phase                       participant          label question                                              clip        event_clip  event_no  frame
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      2
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      3
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      4
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      5
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      6
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      7
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      8
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      9
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     10
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     11
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     12
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     13
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     14
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     15
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     16
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     17
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     18
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     19
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     20
before aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     21

In [10]:
print(df[['participant', 'label', 'question', 'phase', 'clip', 'event_clip', 'event_no', 'frame']].head(20).to_string(index=False))
print()
print(df['phase'].value_counts().to_dict())
print(df['label'].value_counts().to_dict())

                      participant          label question  phase                                              clip        event_clip  event_no  frame
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      2
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      3
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      4
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      5
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      6
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      7
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      8
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1      9
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     10
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     11
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     12
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     13
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     14
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     15
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     16
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     17
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     18
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     19
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     20
aaisyah_nursalsabiil_ni_patriarti anxiety_tinggi       q1 before answer_1_15d591ce-051a-47f2-ac38-367c1e6189c7_sec event_00054-00095         1     21

{'before': 30993, 'after': 26663}
{'anxiety_tinggi': 35980, 'anxiety_rendah': 21676}