# Micro-Expression Spotting — Clip Output

Notebook utama untuk spotting.

Output:
- `/output/apex/metadata.xlsx`
- `/output/apex/dataset/...`

Struktur folder input dipertahankan pada `/output/apex/dataset`.

In [1]:
import gc
import os
import re
import shutil
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path

import cv2
import dlib
import numpy as np
import pandas as pd

PROJECT_ROOT = Path.cwd().resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from apex import ApexPhase, ApexSmoother, ApexPhaseVisualizer
from features_extraction.poc import POC
from features_extraction.quadran import Quadran
from features_extraction.vektor import Vektor
from spotting import SpottingConfig

In [2]:
config = SpottingConfig(
    dataset_root=PROJECT_ROOT / 'dataset' / 'datatest-fix',
    output_root=PROJECT_ROOT / 'output' / 'apex' / 'datatest-fix',
    predictor_path=Path('./models/shape_predictor_68_face_landmarks.dat'),
    video_extensions={'.webm'},
    overwrite=False,
)

max_workers = min(4, os.cpu_count() or 1)

print(f'DATASET_ROOT = {config.dataset_root}')
print(f'OUTPUT_DATASET_ROOT = {config.output_dataset_root}')
print(f'METADATA_PATH = {config.metadata_path}')
print(f"EVENT_SIGNAL_ROOT = {config.output_root / 'event_signals'}")
print(f'MAX_WORKERS = {max_workers}')

DATASET_ROOT = /home/ryuko/skripsi/Skripsi/Convat-1st/dataset/datatest-fix
OUTPUT_DATASET_ROOT = /home/ryuko/skripsi/Skripsi/Convat-1st/output/apex/datatest-fix/dataset
METADATA_PATH = /home/ryuko/skripsi/Skripsi/Convat-1st/output/apex/datatest-fix/metadata.xlsx
EVENT_SIGNAL_ROOT = /home/ryuko/skripsi/Skripsi/Convat-1st/output/apex/datatest-fix/event_signals
MAX_WORKERS = 4

In [3]:
@dataclass(slots=True)
class VideoSample:
    video_path: Path
    relative_parent: Path
    stem: str

    @property
    def relative_video_key(self) -> Path:
        return self.relative_parent / self.stem


WORKER_DETECTOR = None
WORKER_PREDICTOR = None


def init_worker(predictor_path: str) -> None:
    global WORKER_DETECTOR, WORKER_PREDICTOR
    WORKER_DETECTOR = dlib.get_frontal_face_detector()
    WORKER_PREDICTOR = dlib.shape_predictor(predictor_path)


def natural_sort_key(value: str):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', value)]


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def discover_video_samples(dataset_root: Path, video_extensions: set[str]) -> list[VideoSample]:
    samples = []
    for video_path in sorted(dataset_root.rglob('*'), key=lambda p: natural_sort_key(str(p))):
        if not video_path.is_file():
            continue
        if video_path.suffix.lower() not in video_extensions:
            continue
        rel = video_path.relative_to(dataset_root)
        samples.append(VideoSample(video_path=video_path, relative_parent=rel.parent, stem=video_path.stem))
    return samples


def extract_region(image: np.ndarray, landmarks, indices: list[int]) -> np.ndarray:
    pts = [(landmarks.part(i).x, landmarks.part(i).y) for i in indices]
    xs, ys = zip(*pts)
    left = max(0, min(xs) - config.padding_x)
    top = max(0, min(ys) - config.padding_y)
    right = min(image.shape[1], max(xs) + config.padding_x)
    bottom = min(image.shape[0], max(ys) + config.padding_y)
    return image[top:bottom, left:right]


def detect_landmarks(gray: np.ndarray, detector, predictor):
    faces = detector(gray)
    if len(faces) > 0:
        return predictor(gray, faces[0])
    return None


def compute_frame_magnitude(prev_gray, prev_lm, curr_gray, curr_lm) -> float:
    roi_mags = []
    for region_name, lm_indices in config.regions.items():
        try:
            roi_prev = extract_region(prev_gray, prev_lm, lm_indices)
            roi_curr = extract_region(curr_gray, curr_lm, lm_indices)
            if roi_prev.size == 0 or roi_curr.size == 0:
                return 0.0
            target = config.target_size[region_name]
            roi_prev = cv2.resize(roi_prev, target)
            roi_curr = cv2.resize(roi_curr, target)
            poc = POC(roi_prev, roi_curr, config.block_size)
            vec = Vektor(poc.getPOC(), config.block_size)
            quad_data = Quadran(vec.getVektor()).getQuadran()
            magnitudes = [float(block[4]) for block in quad_data]
            roi_mags.append(np.mean(magnitudes) if magnitudes else 0.0)
        except Exception:
            return 0.0
    return float(np.mean(roi_mags)) if roi_mags else 0.0


def load_video_frames(video_path: Path) -> list[np.ndarray]:
    frames = []
    cap = cv2.VideoCapture(str(video_path))
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(frame)
    cap.release()
    return frames


def build_magnitude_signal(frames: list[np.ndarray], detector, predictor) -> list[float]:
    if len(frames) < 3:
        return []
    grays = [cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) for frame in frames]
    magnitudes = []
    prev_gray = grays[0]
    prev_lm = detect_landmarks(prev_gray, detector, predictor)
    for curr_gray in grays[1:]:
        curr_lm = detect_landmarks(curr_gray, detector, predictor)
        if prev_lm is not None and curr_lm is not None:
            mag = compute_frame_magnitude(prev_gray, prev_lm, curr_gray, curr_lm)
        else:
            mag = 0.0
        magnitudes.append(float(mag))
        prev_gray = curr_gray
        prev_lm = curr_lm
    return magnitudes


def detect_events(magnitudes: list[float]) -> tuple[list[float], list[dict], dict]:
    smoothed = ApexSmoother.smooth(magnitudes)
    signal_arr = np.asarray(smoothed, dtype=float)
    height_threshold = float(signal_arr.mean() + signal_arr.std())
    detector = ApexPhase(
        distance_threshold=config.distance_threshold,
        prominence_threshold=config.prominence_threshold,
        cutoff_ratio=config.cutoff_ratio,
    )
    apex_indices = detector.find_top_k_apex(smoothed, k=config.top_k_apex, height=height_threshold)
    phases = detector.find_phase(smoothed, apex_indices) if apex_indices else {}
    events = []
    for event_no, apex_idx in enumerate(apex_indices, start=1):
        phase = phases[apex_idx]
        duration = int(phase['end'] - phase['start'])
        if duration < config.min_phase_duration:
            continue
        events.append({
            'event_no': event_no,
            'onset_signal': int(phase['start']),
            'apex_signal': int(apex_idx),
            'offset_signal': int(phase['end']),
            'duration': duration,
        })
    window_length = ApexSmoother.calculate_window_length(len(magnitudes))
    meta = {
        'window_length': window_length,
        'polyorder': ApexSmoother.calculate_polyorder(window_length),
        'height_threshold': height_threshold,
    }
    return smoothed, events, meta


def signal_index_to_frame_index(signal_index: int) -> int:
    return int(signal_index + 1)


def save_event_clip_frames(frames: list[np.ndarray], sample_output_dir: Path, events: list[dict]) -> list[dict]:
    ensure_dir(sample_output_dir)
    rows = []
    for event in events:
        onset_frame = min(signal_index_to_frame_index(event['onset_signal']), len(frames) - 1)
        apex_frame = min(signal_index_to_frame_index(event['apex_signal']), len(frames) - 1)
        offset_frame = min(signal_index_to_frame_index(event['offset_signal']), len(frames) - 1)
        clip_dir = sample_output_dir / f'event_{onset_frame:05d}-{offset_frame:05d}'
        ensure_dir(clip_dir)
        for write_idx, frame_idx in enumerate(range(onset_frame, offset_frame + 1)):
            if frame_idx == apex_frame:
                out_path = clip_dir / f'frame_{write_idx:05d}-apex.png'
            else:
                out_path = clip_dir / f'frame_{write_idx:05d}.jpg'
            cv2.imwrite(str(out_path), frames[frame_idx])
        rows.append({
            'relative_sample': str(sample_output_dir.relative_to(config.output_dataset_root)),
            'event_no': event['event_no'],
            'onset_signal': event['onset_signal'],
            'apex_signal': event['apex_signal'],
            'offset_signal': event['offset_signal'],
            'onset_frame': onset_frame,
            'apex_frame': apex_frame,
            'offset_frame': offset_frame,
            'duration': event['duration'],
            'saved_frames': offset_frame - onset_frame + 1,
            'clip_dir': str(clip_dir.relative_to(config.output_root)),
        })
    return rows


def process_sample(sample: VideoSample) -> dict:
    detector = WORKER_DETECTOR
    predictor = WORKER_PREDICTOR
    relative_key = sample.relative_video_key
    sample_output_dir = config.output_dataset_root / relative_key

    if sample_output_dir.exists() and not config.overwrite:
        return {
            'status': 'skip',
            'relative_key': str(relative_key),
            'rows': [],
            'reason': 'exists',
        }

    if sample_output_dir.exists() and config.overwrite:
        shutil.rmtree(sample_output_dir)

    frames = load_video_frames(sample.video_path)
    if len(frames) < 3:
        return {
            'status': 'skip',
            'relative_key': str(relative_key),
            'rows': [],
            'reason': f'too few frames ({len(frames)})',
        }

    magnitudes = build_magnitude_signal(frames, detector, predictor)
    if len(magnitudes) < 5:
        return {
            'status': 'skip',
            'relative_key': str(relative_key),
            'rows': [],
            'reason': f'too few magnitudes ({len(magnitudes)})',
        }

    try:
        _smoothed, events, meta = detect_events(magnitudes)
    except ValueError as e:
        return {
            'status': 'skip',
            'relative_key': str(relative_key),
            'rows': [],
            'reason': str(e),
        }

    rows = save_event_clip_frames(frames, sample_output_dir, events)
    metadata_rows = []
    if not rows:
        metadata_rows.append({
            'relative_sample': str(relative_key),
            'source_video': str(sample.video_path),
            'event_no': None,
            'onset_signal': None,
            'apex_signal': None,
            'offset_signal': None,
            'onset_frame': None,
            'apex_frame': None,
            'offset_frame': None,
            'duration': None,
            'saved_frames': 0,
            'window_length': meta['window_length'],
            'polyorder': meta['polyorder'],
            'height_threshold': meta['height_threshold'],
            'clip_dir': None,
        })
    else:
        for row in rows:
            metadata_rows.append({
                'relative_sample': row['relative_sample'],
                'source_video': str(sample.video_path),
                'event_no': row['event_no'],
                'onset_signal': row['onset_signal'],
                'apex_signal': row['apex_signal'],
                'offset_signal': row['offset_signal'],
                'onset_frame': row['onset_frame'],
                'apex_frame': row['apex_frame'],
                'offset_frame': row['offset_frame'],
                'duration': row['duration'],
                'saved_frames': row['saved_frames'],
                'window_length': meta['window_length'],
                'polyorder': meta['polyorder'],
                'height_threshold': meta['height_threshold'],
                'clip_dir': row['clip_dir'],
            })

    del frames
    gc.collect()
    return {
        'status': 'processed',
        'relative_key': str(relative_key),
        'rows': metadata_rows,
        'reason': None,
    }

In [4]:
if not config.dataset_root.exists():
    raise FileNotFoundError(f'Dataset root not found: {config.dataset_root}')
if not config.predictor_path.exists():
    raise FileNotFoundError(f'Predictor not found: {config.predictor_path}')

ensure_dir(config.output_root)
ensure_dir(config.output_dataset_root)
samples = discover_video_samples(config.dataset_root, config.video_extensions)
print(f'Found {len(samples)} video files')
samples[:5]

Found 60 video files

[VideoSample(video_path=PosixPath('/home/ryuko/skripsi/Skripsi/Convat-1st/dataset/datatest-fix/anxiety-rendah/aryan_zuda_firdaus_1776393025300/q1/Aryan Zuda Firdaus_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main.webm'), relative_parent=PosixPath('anxiety-rendah/aryan_zuda_firdaus_1776393025300/q1'), stem='Aryan Zuda Firdaus_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main'),
 VideoSample(video_path=PosixPath('/home/ryuko/skripsi/Skripsi/Convat-1st/dataset/datatest-fix/anxiety-rendah/aryan_zuda_firdaus_1776393025300/q2/Aryan Zuda Firdaus_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main.webm'), relative_parent=PosixPath('anxiety-rendah/aryan_zuda_firdaus_1776393025300/q2'), stem='Aryan Zuda Firdaus_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main'),
 VideoSample(video_path=PosixPath('/home/ryuko/skripsi/Skripsi/Convat-1st/dataset/datatest-fix/anxiety-rendah/aryan_zuda_firdaus_1776393025300/q3/Aryan Zuda Firdaus_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main.webm'), relative_parent=PosixPath('anxiety-rendah/aryan_zuda_firdaus_1776393025300/q3'), stem='Aryan Zuda Firdaus_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main'),
 VideoSample(video_path=PosixPath('/home/ryuko/skripsi/Skripsi/Convat-1st/dataset/datatest-fix/anxiety-rendah/aryan_zuda_firdaus_1776393025300/q4/Aryan Zuda Firdaus_4_497eb431-dd00-4530-858f-e8ec710014e7_main.webm'), relative_parent=PosixPath('anxiety-rendah/aryan_zuda_firdaus_1776393025300/q4'), stem='Aryan Zuda Firdaus_4_497eb431-dd00-4530-858f-e8ec710014e7_main'),
 VideoSample(video_path=PosixPath('/home/ryuko/skripsi/Skripsi/Convat-1st/dataset/datatest-fix/anxiety-rendah/aryan_zuda_firdaus_1776393025300/q5/Aryan Zuda Firdaus_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main.webm'), relative_parent=PosixPath('anxiety-rendah/aryan_zuda_firdaus_1776393025300/q5'), stem='Aryan Zuda Firdaus_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main')]

In [5]:
metadata_rows = []
total_samples = len(samples)
predictor_path = str(config.predictor_path)

with ProcessPoolExecutor(
    max_workers=max_workers,
    initializer=init_worker,
    initargs=(predictor_path,),
) as executor:
    futures = {executor.submit(process_sample, sample): sample for sample in samples}
    completed = 0
    for future in as_completed(futures):
        sample = futures[future]
        relative_key = sample.relative_video_key
        completed += 1
        try:
            result = future.result()
        except Exception as e:
            print(f'[{completed}/{total_samples}] fail {relative_key}: {e}')
            continue

        if result['status'] == 'skip':
            print(f"[{completed}/{total_samples}] skip {result['relative_key']}: {result['reason']}")
            continue

        print(f"[{completed}/{total_samples}] process {result['relative_key']}")
        metadata_rows.extend(result['rows'])

metadata_df = pd.DataFrame(metadata_rows)
metadata_df.to_excel(config.metadata_path, index=False)
print(f'Saved metadata: {config.metadata_path}')
print(metadata_df.head())
metadata_df

[1/60] skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q1/Aryan Zuda Firdaus_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[2/60] skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q2/Aryan Zuda Firdaus_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[3/60] skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q3/Aryan Zuda Firdaus_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[4/60] skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q4/Aryan Zuda Firdaus_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[5/60] skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q5/Aryan Zuda Firdaus_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[6/60] skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q1/Dewi Anggraini Meita Sari_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[7/60] skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q2/Dewi Anggraini Meita Sari_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[8/60] skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q3/Dewi Anggraini Meita Sari_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[9/60] skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q4/Dewi Anggraini Meita Sari_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[10/60] skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q5/Dewi Anggraini Meita Sari_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[11/60] skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q1/Ilham Dharma Atmaja_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[12/60] skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q2/Ilham Dharma Atmaja_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[13/60] skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q3/Ilham Dharma Atmaja_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[14/60] skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q4/Ilham Dharma Atmaja_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[15/60] skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q5/Ilham Dharma Atmaja_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[16/60] skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q1/Muhammad Christiano Olyvian Barini_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[17/60] skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q2/Muhammad Christiano Olyvian Barini_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[18/60] skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q3/Muhammad Christiano Olyvian Barini_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[19/60] skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q4/Muhammad Christiano Olyvian Barini_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[20/60] skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q5/Muhammad Christiano Olyvian Barini_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[21/60] skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q1/Muhammad Daniel Assaqovi_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[22/60] skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q2/Muhammad Daniel Assaqovi_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[23/60] skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q3/Muhammad Daniel Assaqovi_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[24/60] skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q4/Muhammad Daniel Assaqovi_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[25/60] skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q5/Muhammad Daniel Assaqovi_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[26/60] skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q1/Rachmad Aprisandhy_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[27/60] skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q2/Rachmad Aprisandhy_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[28/60] skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q3/Rachmad Aprisandhy_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[29/60] skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q4/Rachmad Aprisandhy_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[30/60] skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q5/Rachmad Aprisandhy_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[31/60] skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q1/Sileysa Faedatul Nuraini_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[32/60] skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q2/Sileysa Faedatul Nuraini_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[33/60] skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q3/Sileysa Faedatul Nuraini_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[34/60] skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q4/Sileysa Faedatul Nuraini_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[35/60] skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q5/Sileysa Faedatul Nuraini_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[36/60] skip anxiety-tinggi/abim_mustawa_1776388618012/q1/Abim Mustawa_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[37/60] skip anxiety-tinggi/abim_mustawa_1776388618012/q2/Abim Mustawa_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[38/60] skip anxiety-tinggi/abim_mustawa_1776388618012/q3/Abim Mustawa_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[39/60] skip anxiety-tinggi/abim_mustawa_1776388618012/q4/Abim Mustawa_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[40/60] skip anxiety-tinggi/abim_mustawa_1776388618012/q5/Abim Mustawa_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[41/60] skip anxiety-tinggi/ahmad_falahi_1776231796987/q1/Ahmad Falahi_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[42/60] skip anxiety-tinggi/ahmad_falahi_1776231796987/q2/Ahmad Falahi_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[43/60] skip anxiety-tinggi/ahmad_falahi_1776231796987/q3/Ahmad Falahi_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[44/60] skip anxiety-tinggi/ahmad_falahi_1776231796987/q4/Ahmad Falahi_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[45/60] skip anxiety-tinggi/ahmad_falahi_1776231796987/q5/Ahmad Falahi_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[46/60] skip anxiety-tinggi/dicky_darmawan_1776223634878/q1/Dicky Darmawan_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[47/60] skip anxiety-tinggi/dicky_darmawan_1776223634878/q2/Dicky Darmawan_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[48/60] skip anxiety-tinggi/dicky_darmawan_1776223634878/q3/Dicky Darmawan_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[49/60] skip anxiety-tinggi/dicky_darmawan_1776223634878/q4/Dicky Darmawan_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[50/60] skip anxiety-tinggi/dicky_darmawan_1776223634878/q5/Dicky Darmawan_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[51/60] skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q1/Muhammad Nuril Huda_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[52/60] skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q2/Muhammad Nuril Huda_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[53/60] skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q3/Muhammad Nuril Huda_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[54/60] skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q4/Muhammad Nuril Huda_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[55/60] skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q5/Muhammad Nuril Huda_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
[56/60] skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q1/Naufal Ramadhan Wahyudiansyah_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: exists
[57/60] skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q2/Naufal Ramadhan Wahyudiansyah_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: exists
[58/60] skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q3/Naufal Ramadhan Wahyudiansyah_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: exists
[59/60] skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q4/Naufal Ramadhan Wahyudiansyah_4_497eb431-dd00-4530-858f-e8ec710014e7_main: exists
[60/60] skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q5/Naufal Ramadhan Wahyudiansyah_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: exists
Saved metadata: /home/ryuko/skripsi/Skripsi/Convat-1st/output/apex/datatest-fix/metadata.xlsx
Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

In [6]:
event_signal_root = config.output_root / 'event_signals'
ensure_dir(event_signal_root)

signal_rows = []
visualizer = ApexPhaseVisualizer()

for sample in samples:
    relative_key = sample.relative_video_key
    signal_path = event_signal_root / relative_key.with_suffix('.xlsx')
    plot_path = event_signal_root / relative_key.with_suffix('.png')

    if signal_path.exists() and plot_path.exists() and not config.overwrite:
        print(f'skip {relative_key}: event signal exists')
        continue

    frames = load_video_frames(sample.video_path)
    if len(frames) < 3:
        print(f'skip {relative_key}: too few frames ({len(frames)})')
        continue

    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor(str(config.predictor_path))
    magnitudes = build_magnitude_signal(frames, detector, predictor)
    if len(magnitudes) < 5:
        print(f'skip {relative_key}: too few magnitudes ({len(magnitudes)})')
        continue

    try:
        smoothed, events, meta = detect_events(magnitudes)
    except ValueError as e:
        print(f'skip {relative_key}: {e}')
        continue

    event_by_apex = {event['apex_signal']: event for event in events}
    phases = {
        event['apex_signal']: {'start': event['onset_signal'], 'end': event['offset_signal']}
        for event in events
    }
    apex_indices = list(event_by_apex)

    rows = []
    for idx, (raw_value, smooth_value) in enumerate(zip(magnitudes, smoothed)):
        event = event_by_apex.get(idx)
        marker = ''
        event_no = None
        if event is not None:
            marker = 'apex'
            event_no = event['event_no']
        else:
            for candidate in events:
                if idx == candidate['onset_signal']:
                    marker = 'onset'
                    event_no = candidate['event_no']
                    break
                if idx == candidate['offset_signal']:
                    marker = 'offset'
                    event_no = candidate['event_no']
                    break
        rows.append({
            'relative_sample': str(relative_key),
            'source_video': str(sample.video_path),
            'signal_index': idx,
            'frame_index': signal_index_to_frame_index(idx),
            'raw_magnitude': raw_value,
            'smoothed_magnitude': smooth_value,
            'height_threshold': meta['height_threshold'],
            'event_marker': marker,
            'event_no': event_no,
        })

    signal_path.parent.mkdir(parents=True, exist_ok=True)
    plot_path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_excel(signal_path, index=False)

    if apex_indices:
        visualizer.plot_phases(
            signal=smoothed,
            apex_indices=apex_indices,
            phases=phases,
            title=f'Micro-Expression Spotting: {relative_key}',
            save_path=str(plot_path),
        )

    signal_rows.append({
        'relative_sample': str(relative_key),
        'source_video': str(sample.video_path),
        'signal_excel': str(signal_path.relative_to(config.output_root)),
        'plot_path': str(plot_path.relative_to(config.output_root)) if apex_indices else None,
        'total_frames': len(frames),
        'total_magnitudes': len(magnitudes),
        'event_count': len(events),
        'window_length': meta['window_length'],
        'polyorder': meta['polyorder'],
        'height_threshold': meta['height_threshold'],
    })
    print(f'saved {relative_key}: {len(events)} events -> {signal_path}')

signal_index_df = pd.DataFrame(signal_rows)
signal_index_path = event_signal_root / 'index.xlsx'
signal_index_df.to_excel(signal_index_path, index=False)
print(f'Saved event signal index: {signal_index_path}')
signal_index_df

skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q1/Aryan Zuda Firdaus_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q2/Aryan Zuda Firdaus_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q3/Aryan Zuda Firdaus_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q4/Aryan Zuda Firdaus_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-rendah/aryan_zuda_firdaus_1776393025300/q5/Aryan Zuda Firdaus_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q1/Dewi Anggraini Meita Sari_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q2/Dewi Anggraini Meita Sari_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q3/Dewi Anggraini Meita Sari_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q4/Dewi Anggraini Meita Sari_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-rendah/dewi_anggraini_meita_sari_1776228142858/q5/Dewi Anggraini Meita Sari_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q1/Ilham Dharma Atmaja_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q2/Ilham Dharma Atmaja_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q3/Ilham Dharma Atmaja_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q4/Ilham Dharma Atmaja_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-rendah/ilham_dharma_atmaja_1776395335293/q5/Ilham Dharma Atmaja_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q1/Muhammad Christiano Olyvian Barini_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q2/Muhammad Christiano Olyvian Barini_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q3/Muhammad Christiano Olyvian Barini_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q4/Muhammad Christiano Olyvian Barini_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-rendah/muhammad_christiano_olyvian_barini_1776391962326/q5/Muhammad Christiano Olyvian Barini_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q1/Muhammad Daniel Assaqovi_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q2/Muhammad Daniel Assaqovi_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q3/Muhammad Daniel Assaqovi_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q4/Muhammad Daniel Assaqovi_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-rendah/muhammad_daniel_assaqovi_1776223534834/q5/Muhammad Daniel Assaqovi_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q1/Rachmad Aprisandhy_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q2/Rachmad Aprisandhy_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q3/Rachmad Aprisandhy_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q4/Rachmad Aprisandhy_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-rendah/rachmad_aprisandhy_1776396904266/q5/Rachmad Aprisandhy_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q1/Sileysa Faedatul Nuraini_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q2/Sileysa Faedatul Nuraini_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q3/Sileysa Faedatul Nuraini_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q4/Sileysa Faedatul Nuraini_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-rendah/sileysa_faedatul_nuraini_1776227906081/q5/Sileysa Faedatul Nuraini_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-tinggi/abim_mustawa_1776388618012/q1/Abim Mustawa_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-tinggi/abim_mustawa_1776388618012/q2/Abim Mustawa_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-tinggi/abim_mustawa_1776388618012/q3/Abim Mustawa_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-tinggi/abim_mustawa_1776388618012/q4/Abim Mustawa_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-tinggi/abim_mustawa_1776388618012/q5/Abim Mustawa_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-tinggi/ahmad_falahi_1776231796987/q1/Ahmad Falahi_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-tinggi/ahmad_falahi_1776231796987/q2/Ahmad Falahi_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-tinggi/ahmad_falahi_1776231796987/q3/Ahmad Falahi_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-tinggi/ahmad_falahi_1776231796987/q4/Ahmad Falahi_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-tinggi/ahmad_falahi_1776231796987/q5/Ahmad Falahi_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-tinggi/dicky_darmawan_1776223634878/q1/Dicky Darmawan_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-tinggi/dicky_darmawan_1776223634878/q2/Dicky Darmawan_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-tinggi/dicky_darmawan_1776223634878/q3/Dicky Darmawan_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-tinggi/dicky_darmawan_1776223634878/q4/Dicky Darmawan_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-tinggi/dicky_darmawan_1776223634878/q5/Dicky Darmawan_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q1/Muhammad Nuril Huda_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q2/Muhammad Nuril Huda_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q3/Muhammad Nuril Huda_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q4/Muhammad Nuril Huda_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-tinggi/muhammad_nuril_huda_1776225667623/q5/Muhammad Nuril Huda_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q1/Naufal Ramadhan Wahyudiansyah_1_15d591ce-051a-47f2-ac38-367c1e6189c7_main: event signal exists
skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q2/Naufal Ramadhan Wahyudiansyah_2_490a0a4a-d935-4509-9a4e-fb0a393be5b9_main: event signal exists
skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q3/Naufal Ramadhan Wahyudiansyah_3_ce8ef7e8-63e6-46c1-a510-1b8269c27ce7_main: event signal exists
skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q4/Naufal Ramadhan Wahyudiansyah_4_497eb431-dd00-4530-858f-e8ec710014e7_main: event signal exists
skip anxiety-tinggi/naufal_ramadhan_wahyudiansyah_1776225673074/q5/Naufal Ramadhan Wahyudiansyah_5_e1e6b3e5-a2d1-4832-a1fc-e03673252751_main: event signal exists
Saved event signal index: /home/ryuko/skripsi/Skripsi/Convat-1st/output/apex/datatest-fix/event_signals/index.xlsx

Empty DataFrame
Columns: []
Index: []